name: oasis

volumes:
  postgres-storage:

networks:
  app-tier:

services:
  postgres:
    image: bitnami/postgresql:16-debian-12
    networks:
      - app-tier
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: unless-stopped
    volumes:
      - postgres-storage:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: goasis_api
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD}
