// Code generated by mockery v2.45.0. DO NOT EDIT.

package mockport

import (
	context "context"

	model "github.com/isutare412/goasis/internal/core/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCafeRepository is an autogenerated mock type for the CafeRepository type
type MockCafeRepository struct {
	mock.Mock
}

type MockCafeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCafeRepository) EXPECT() *MockCafeRepository_Expecter {
	return &MockCafeRepository_Expecter{mock: &_m.Mock}
}

// CreateCafe provides a mock function with given fields: _a0, _a1
func (_m *MockCafeRepository) CreateCafe(_a0 context.Context, _a1 model.Cafe) (model.Cafe, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateCafe")
	}

	var r0 model.Cafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Cafe) (model.Cafe, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Cafe) model.Cafe); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Cafe)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Cafe) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCafeRepository_CreateCafe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCafe'
type MockCafeRepository_CreateCafe_Call struct {
	*mock.Call
}

// CreateCafe is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.Cafe
func (_e *MockCafeRepository_Expecter) CreateCafe(_a0 interface{}, _a1 interface{}) *MockCafeRepository_CreateCafe_Call {
	return &MockCafeRepository_CreateCafe_Call{Call: _e.mock.On("CreateCafe", _a0, _a1)}
}

func (_c *MockCafeRepository_CreateCafe_Call) Run(run func(_a0 context.Context, _a1 model.Cafe)) *MockCafeRepository_CreateCafe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Cafe))
	})
	return _c
}

func (_c *MockCafeRepository_CreateCafe_Call) Return(created model.Cafe, err error) *MockCafeRepository_CreateCafe_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *MockCafeRepository_CreateCafe_Call) RunAndReturn(run func(context.Context, model.Cafe) (model.Cafe, error)) *MockCafeRepository_CreateCafe_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCafe provides a mock function with given fields: ctx, id
func (_m *MockCafeRepository) DeleteCafe(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCafe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCafeRepository_DeleteCafe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCafe'
type MockCafeRepository_DeleteCafe_Call struct {
	*mock.Call
}

// DeleteCafe is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCafeRepository_Expecter) DeleteCafe(ctx interface{}, id interface{}) *MockCafeRepository_DeleteCafe_Call {
	return &MockCafeRepository_DeleteCafe_Call{Call: _e.mock.On("DeleteCafe", ctx, id)}
}

func (_c *MockCafeRepository_DeleteCafe_Call) Run(run func(ctx context.Context, id int64)) *MockCafeRepository_DeleteCafe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCafeRepository_DeleteCafe_Call) Return(_a0 error) *MockCafeRepository_DeleteCafe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCafeRepository_DeleteCafe_Call) RunAndReturn(run func(context.Context, int64) error) *MockCafeRepository_DeleteCafe_Call {
	_c.Call.Return(run)
	return _c
}

// GetCafe provides a mock function with given fields: ctx, id
func (_m *MockCafeRepository) GetCafe(ctx context.Context, id int64) (model.Cafe, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCafe")
	}

	var r0 model.Cafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Cafe, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Cafe); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Cafe)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCafeRepository_GetCafe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCafe'
type MockCafeRepository_GetCafe_Call struct {
	*mock.Call
}

// GetCafe is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCafeRepository_Expecter) GetCafe(ctx interface{}, id interface{}) *MockCafeRepository_GetCafe_Call {
	return &MockCafeRepository_GetCafe_Call{Call: _e.mock.On("GetCafe", ctx, id)}
}

func (_c *MockCafeRepository_GetCafe_Call) Run(run func(ctx context.Context, id int64)) *MockCafeRepository_GetCafe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCafeRepository_GetCafe_Call) Return(_a0 model.Cafe, _a1 error) *MockCafeRepository_GetCafe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCafeRepository_GetCafe_Call) RunAndReturn(run func(context.Context, int64) (model.Cafe, error)) *MockCafeRepository_GetCafe_Call {
	_c.Call.Return(run)
	return _c
}

// ListCafes provides a mock function with given fields: _a0
func (_m *MockCafeRepository) ListCafes(_a0 context.Context) ([]model.Cafe, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListCafes")
	}

	var r0 []model.Cafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Cafe, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Cafe); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Cafe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCafeRepository_ListCafes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCafes'
type MockCafeRepository_ListCafes_Call struct {
	*mock.Call
}

// ListCafes is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockCafeRepository_Expecter) ListCafes(_a0 interface{}) *MockCafeRepository_ListCafes_Call {
	return &MockCafeRepository_ListCafes_Call{Call: _e.mock.On("ListCafes", _a0)}
}

func (_c *MockCafeRepository_ListCafes_Call) Run(run func(_a0 context.Context)) *MockCafeRepository_ListCafes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCafeRepository_ListCafes_Call) Return(_a0 []model.Cafe, _a1 error) *MockCafeRepository_ListCafes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCafeRepository_ListCafes_Call) RunAndReturn(run func(context.Context) ([]model.Cafe, error)) *MockCafeRepository_ListCafes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCafe provides a mock function with given fields: _a0, _a1
func (_m *MockCafeRepository) UpdateCafe(_a0 context.Context, _a1 model.Cafe) (model.Cafe, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCafe")
	}

	var r0 model.Cafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Cafe) (model.Cafe, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Cafe) model.Cafe); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Cafe)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Cafe) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCafeRepository_UpdateCafe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCafe'
type MockCafeRepository_UpdateCafe_Call struct {
	*mock.Call
}

// UpdateCafe is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.Cafe
func (_e *MockCafeRepository_Expecter) UpdateCafe(_a0 interface{}, _a1 interface{}) *MockCafeRepository_UpdateCafe_Call {
	return &MockCafeRepository_UpdateCafe_Call{Call: _e.mock.On("UpdateCafe", _a0, _a1)}
}

func (_c *MockCafeRepository_UpdateCafe_Call) Run(run func(_a0 context.Context, _a1 model.Cafe)) *MockCafeRepository_UpdateCafe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Cafe))
	})
	return _c
}

func (_c *MockCafeRepository_UpdateCafe_Call) Return(updated model.Cafe, err error) *MockCafeRepository_UpdateCafe_Call {
	_c.Call.Return(updated, err)
	return _c
}

func (_c *MockCafeRepository_UpdateCafe_Call) RunAndReturn(run func(context.Context, model.Cafe) (model.Cafe, error)) *MockCafeRepository_UpdateCafe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCafeRepository creates a new instance of MockCafeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCafeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCafeRepository {
	mock := &MockCafeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
